<?php
/**
 * @file
 * jnl_bmj.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function jnl_bmj_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "panels_mini" && $api == "panels_default") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function jnl_bmj_node_info() {
  $items = array(
    'bmj_additional_article_data' => array(
      'name' => t('BMJ: Additional Article Data'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}
