<?php



function secure_file_menu()
{
	 $items = array();

  $items['fileviewer/%'] = array(
    'title'             => 'Securing the File Viewer',
    'page callback'    => 'secure_file_download',
    'page arguments'   => array(1),
   'access callback' => 'user_is_logged_in',
    'access' => TRUE,
    'description'       => 'Manage settings for the ABI iMIS authentication module including authentication URL and optional extra permission checks',
  );

  return $items;

}
function secure_file_download($args)
{
	$fileinfo = get_fileinfo($args);

}
function get_fileinfo($fid){
	global $user;
	
	$query = db_select('file_managed', 'f');
	$query->condition('f.fid', $fid, '=')
	      ->fields('f', array('fid', 'filename','filemime','uri'))
	      ->range(0, 1);
	$result = $query->execute();
	
	foreach($result as $item){
		$item->filename = "/var/www/abid7/sites/default/files/media/".$item->filename;
		if (file_exists($item->filename)) {
			$password = $user->mail;

			//name of the original file (unprotected)
			$origFile = $item->filename;

			//name of the destination file (password protected and printing rights removed)
			$destFile = "/var/www/abid7/sites/default/files/media/".check_plain($user->name)."_proctected_".basename($item->filename);
			echo $destFile;
			//encrypt the book and create the protected file
			$returnedFile = pdfEncrypt($origFile, $password, $destFile );
			//readfile($returnedFile);
		    header('Content-Description: File Transfer');
		    header('Content-Type: application/octet-stream');
		    header('Content-Disposition: attachment; filename='.basename($returnedFile));
		    header('Content-Transfer-Encoding: binary');
		    header('Expires: 0');
		    header('Cache-Control: must-revalidate');
		    header('Pragma: public');
		    header('Content-Length: ' . filesize($returnedFile));
		    ob_clean();
		    flush();
		    readfile($returnedFile);
		    //password for the pdf file
			
		}
	}
	
}
function pdfEncrypt ($origFile, $password, $destFile){

	require('pdfrotator.inc');
	$pdf = new PDF();

    if (file_exists($origFile)){
        $pagecount = $pdf->setSourceFile($origFile);
    } else {
        return FALSE;
    }

   $pdf->setWaterText("w a t e r M a r k d e m o ", "s e c o n d L i n e o f t e x t");

  /* loop for multipage pdf */
   for($i=1; $i <= $pagecount; $i++) { 
     $tpl = $pdf->importPage($i);               
     $pdf->addPage(); 
     $pdf->useTemplate($tpl, 1, 1, 0, 0, TRUE);  
   }
    $pdf->Output($destFile); //specify path filename to save or keep as it is to view in browser
    return $pdf->Output($destFile);
	}

	